name: rate limiter CI
on:
  push:
    branches:
      - main
jobs:
  dynamic-version-bump:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Extract source branch name and determine bump type
        id: extract_branch_and_bump
        run: |
          # Get the branch name from the push event
          BRANCH_NAME=$(git log -1 --pretty=%B | sed -n 's/.*Merge pull request #.* from //p')

          # Extract the prefix (major, minor, patch) from the branch name
          VERSION_BUMP=$(echo "$BRANCH_NAME" | awk -F'/' '{print tolower($1)}')

          # Validate the bump type
          case "$VERSION_BUMP" in
            major|minor|patch) 
              echo "Valid version bump: $VERSION_BUMP";;
            *)
              echo "Invalid version bump type. Defaulting to patch."
              VERSION_BUMP="patch";;
          esac

          echo "Branch name: $BRANCH_NAME"
          echo "Version bump type: $VERSION_BUMP"
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
          echo "VERSION_BUMP=$VERSION_BUMP" >> $GITHUB_ENV

      - name: Get current version tag and bump if exists
        id: get_version
        run: |
          # Get the latest tag, default to 0.0.0 if no tags exist
          VERSION=$(git describe --tags --abbrev=0 2>/dev/null || echo "0.0.0")
          echo "Current version: $VERSION"

          # Parse the version into MAJOR, MINOR, PATCH
          IFS='.' read -r MAJOR MINOR PATCH <<< "${VERSION//v/}"

          # Check if the tag already exists and increment if needed
          while git rev-parse "v$MAJOR.$MINOR.$PATCH" >/dev/null 2>&1; do
            case "$VERSION_BUMP" in
              major)
                MAJOR=$((MAJOR + 1))
                MINOR=0
                PATCH=0
                ;;
              minor)
                MINOR=$((MINOR + 1))
                PATCH=0
                ;;
              patch)
                PATCH=$((PATCH + 1))
                ;;
            esac
          done

          # Create new version
          NEW_VERSION="v$MAJOR.$MINOR.$PATCH"
          echo "New version: $NEW_VERSION"
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
          echo "::set-output name=new_version::$NEW_VERSION"

      - name: Create and push new tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git tag $NEW_VERSION
          git push origin $NEW_VERSION
          echo "Created and pushed new tag: $NEW_VERSION"
